Muestra_crud_excel/GrupoGD_Test/Controllers/EmpleadoController.cs
using Entidad;
using LogicaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrupoGD_Test.Controllers
{
    public class EmpleadoController : Controller
    {

        private EmpleadoLN empBL = new EmpleadoLN();


        public JsonResult AgregarEmpleado(EmpleadoET emp)
        {
            bool response = empBL.AgregarEmpleado(emp);



            return Json(response);  //true = exito, false = fallo
        }


        public JsonResult EliminarEmpleado(string dui)
        {
            bool response = empBL.EliminarEmpleado(dui);



            return Json(response);  //true = exito, false = fallo
        }


        public JsonResult ActualizarEmpleado(EmpleadoET emp)
        {
            bool response = empBL.ActualizarEmpleado(emp);

            return Json(response);  //true = exito, false = fallo
        }

    }
}

Muestra_crud_excel/GrupoGD_Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidad;
using LogicaNegocio;
using System.Data;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace GrupoGD_Test.Controllers
{
    public class HomeController : Controller
    {
        private EmpleadoLN empBL = new EmpleadoLN();

        [HttpGet]
        public ActionResult Index()
        {
            List<EmpleadoET> empList = empBL.empleadoList(); //buscar todos los empleados

            

            ViewBag.empList = empList; //llena la lista con los empleados de la base de datos            

            return View();
        }






        [HttpPost]
        public ActionResult Index(HttpPostedFileBase archivo, string consulta)
        {

            string ruta1 = System.IO.Path.GetDirectoryName(archivo.FileName);
            string ruta = "";
            if (archivo != null)
            {
                ruta = Server.MapPath("~/Temp/");
                ruta += archivo.FileName;
                archivo.SaveAs(ruta);
            }

            bool response = empBL.ImportarArchiv(ruta);
            ViewBag.consulta = false;

            List<EmpleadoET> empList = empBL.empleadoList();
            ViewBag.empList = empList;

            return View("Index");


        }

        public JsonResult ExportarArchivo()
        {
            string ruta = Server.MapPath("~/Temp/");
            string nombre_archivo= "evaluación_" + DateTime.Now.Day+"-"+ DateTime.Now.Month+"-"+DateTime.Now.Year+"_"+ DateTime.Now.Minute + DateTime.Now.Second + ".xlsx";
            ruta += nombre_archivo;

            

            bool result= empBL.ExportarArchivo(ruta);

            if (result)
            {
                return Json(nombre_archivo);
            }
            else
            {
                return Json(result);
            }

              //true = exito, false = fallo
        }






        
    }
}

Muestra_crud_excel/GrupoGD_Test/Controllers/ReporteController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using LogicaNegocio;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrupoGD_Test.Controllers
{
    public class ReporteController : Controller
    {
        private EmpleadoLN empBL = new EmpleadoLN();
        // GET: Reporte
        public FileResult Index()
        {
            MemoryStream workStream = new MemoryStream();
            Document document = new Document();
            PdfWriter.GetInstance(document, workStream).CloseStream = false;
            DataTable dt = new DataTable();
            dt = empBL.busquedaReporte();
            if (dt.Rows.Count > 0)
            {
                document.Open();
                Font fontTitle = FontFactory.GetFont(FontFactory.COURIER_BOLD, 25);
                Font font9 = FontFactory.GetFont(FontFactory.TIMES, 9);


                PdfPTable table = new PdfPTable(dt.Columns.Count);
                document.Add(new Paragraph(20, "Reporte de Empleados Mayores de 30", fontTitle));
                document.Add(new Chunk("\n"));

                float[] widths = new float[dt.Columns.Count];
                for (int i = 0; i < dt.Columns.Count; i++)
                    widths[i] = 4f;

                table.SetWidths(widths);
                table.WidthPercentage = 90;

                PdfPCell cell = new PdfPCell(new Phrase("columns"));
                cell.Colspan = dt.Columns.Count;

                foreach (DataColumn c in dt.Columns)
                {
                    table.AddCell(new Phrase(c.ColumnName, font9));
                }

                foreach (DataRow r in dt.Rows)
                {
                    if (dt.Rows.Count > 0)
                    {
                        for (int h = 0; h < dt.Columns.Count; h++)
                        {
                            table.AddCell(new Phrase(r[h].ToString(), font9));
                        }
                    }
                }
                document.Add(table);
            }
            document.Close();

            byte[] byteInfo = workStream.ToArray();
            workStream.Write(byteInfo, 0, byteInfo.Length);
            workStream.Position = 0;

            return File(byteInfo, "application/pdf", "ReporteEmpleados.pdf");

            //return View();
        }
    }
}

Muestra_crud_excel/GrupoGD_Test/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Muestra_crud_excel/GrupoGD_Test/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Muestra_crud_excel/GrupoGD_Test/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Ingreso Empleados";
}

<form id="frmIngresoEmpleado" method="post" enctype="multipart/form-data">
    <div class="row">
        <br />
       
        <div class="form-group col-md-12">

            <label for="txtNombre"> Nombres</label>
            <input id="txtNombre" type="text" class="form-control" />
        </div>
        <div class="form-group col-md-12">
            <label for="txtApellido"> Apellidos</label>
            <input id="txtApellido" type="text" class="form-control" />
        </div>

        <div class="form-group col-xs-12 col-sm-6 col-md-3 col-lg-3">
            <label for="datetimepicker1">Fecha Nacimiento</label>
            <div class='input-group date' id='datetimepicker1'>
                <input id="txt_dtpicker1" type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <br> <br> <br> <br>
        <div class=" form-group col-md-12">
            <label for="txtDui">DUI</label>
            <input id="txtDui" type="text" class="form-control" />
        </div>

        <div class=" form-group col-md-12">
            <label for="txtNit">NIT</label>
            <input id="txtNit" type="text" class="form-control" />
        </div>

        <div class="form-group col-md-12">
            <label for="txtIsss">ISSS</label>
            <input id="txtIsss" type="text" class="form-control" />
        </div>


        <div class="form-group col-md-12">
            <label for="txtTelefono">Telefono</label>
            <input id="txtTelefono" type="text" class="form-control" />
        </div>


        <br>
        <div class="form-group col-md-12">
            <label for="txtImportar">Para Importar</label>
            <input id="archivo" name="archivo" type="file" class="form-control" />
        </div>

        <input id="consulta" name="consulta" value="s" hidden/>
    </div>

    <br> 
    <div class="row">
        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            <button class="btn-success form-control" type="button" id="btn_agregar"> Agregar <span class="glyphicon glyphicon-floppy-saved"></span></button>
        </div>
        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            <button class="btn-primary form-control" type="button" id="btn_modificar"> Modificar <span class="glyphicon glyphicon-edit"></span></button>
        </div>
        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            <button class="btn-danger form-control" type="button" id="btn_eliminar"> Eliminar <span class="glyphicon glyphicon-remove-circle"></span></button>
        </div>
        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            <button class="btn-info form-control" type="submit" id="btn_importar"> Importar <span class="glyphicon glyphicon-open"></span></button>
        </div>
        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            <button class="btn-info form-control" type="button" id="btn_exportar"> Exportar <span class="glyphicon glyphicon-save"></span></button>
        </div>

        <div class="form-group col-xs-6 col-sm-3 col-md-2 col-lg-2">
            @*<button class="btn-info form-control" type="button" id="btn_reporte"> Reporte <span class="glyphicon glyphicon-save"></span></button>*@
            <button id="btn_reporte" type="button" class="btn-info form-control" onclick="@("window.location.href='" + @Url.Action("Index", "Reporte") + "'");">Reporte
                <span class="glyphicon glyphicon-file"></span>
            </button>

</div>
    </div>

    <br> 
    <div class="row">
        <table id="tblEmpleado" class="table-bordered col-md-12">
            <thead>
                <tr>
                    <th>
                        Nombres
                    </th>
                    <th>
                        Apellidos
                    </th>
                    <th>
                        Fecha Nacimiento
                    </th>
                    <th>
                        DUI
                    </th>
                    <th>
                       NIT
                    </th>
                    <th>
                       ISSS
                    </th>
                    <th>
                        Telefono
                    </th>
                    <th>

                    </th>
                </tr>

            </thead>
            <tbody>
                @foreach (var item in ViewBag.empList)
                {
                    <tr >
                        <td>@item.nombre</td>
                        <td>@item.apellido</td>
                        <td>@item.fechaNacimiento</td>
                        <td>@item.dui</td>
                        <td>@item.nit</td>
                        <td>@item.isss</td>
                        <td>@item.telefono</td>
                        <td id="@item.dui" class="editar"><a data-toggle="tooltip" data-placement="top" title="Modificar" onclick="" class=" delete-color"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</form>

Muestra_crud_excel/GrupoGD_Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ingreso Empleados ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Karla Villavicencio - Prueba </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.mask.js"></script>
    <link href="~/Scripts/style/bootstrap-datetimepicker.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script src="~/Scripts/js/Empleado.js"></script>


</body>
</html>